/**
 * Terminal configuration — constants, action codes, virtual file system.
 */

/* ═══════════════  Agent Hashes (SHA-256)  ═══════════════
   456D79 → emy
   4C6561 → lea
   ════════════════════════════════════════════════════════ */

export const AGENT_HASHES = {
  '1c1ba6c2628afd47c9e1c57cf6ac548daedfc75a71874f0f2a10c84dbb1640fe': 'emy',
  '130111a9374da4888cf316006ce27b082c6dc1c90bcdd4aa2b5cae31a347808f': 'lea',
};

/* ═══════════════  Admin Hash (SHA-256)  ═══════════════
   61646D → Security Admin
   ════════════════════════════════════════════════════════ */

export const STAFF_HASHES = {
  'c6d898f8cd695542b595cef666337f2a42b012b5b163227679c89bbcb180ea27': { name: 'ADMIN', role: 'Administration Sécurité' },
};

/* ═══════════════  Promote Tier Codes  ═══════════════ */

export const PROMOTE_CODES = {
  '546967232':  2,
  '110819805':  3,
  '999999999':  4,
};

/* ═══════════════  Terminal Colors  ═══════════════
   Each physical terminal uses ?t=1, ?t=2, ?t=3 in the URL.
   The COLOR command (Tier 4) reveals which color this terminal is.
   ════════════════════════════════════════════════════════ */

export const TERMINAL_COLORS = {
  '1': { color: 'RED',    label: 'ROUGE',  css: '#ff3040' },
  '2': { color: 'BLUE',   label: 'BLEU',   css: '#4488ff' },
  '3': { color: 'YELLOW', label: 'JAUNE',  css: '#f5c542' },
};

/* ═══════════════  Override Codes  ═══════════════
   The right keycard code must be entered on the matching-color terminal.
   OVERRIDE <code> checks: code → expected color, terminal color must match.
   ════════════════════════════════════════════════════════ */

export const OVERRIDE_CODES = {
  '524544':       'RED',     // Carte Rouge
  '424C5545':     'BLUE',    // Carte Bleue
  '59454C4C4F57': 'YELLOW',  // Carte Jaune
};

export const INACTIVITY_TIMEOUT = 60000; // 25 seconds

/* ═══════════════  Boot Sequence  ═══════════════ */

export const BOOT_LINES = [
  { text: 'SEFY FACILITY TERMINAL v2.4.1', delay: 600, cls: 'dim' },
  { text: 'Initialisation du système…', delay: 800, cls: '' },
  { text: 'Connexion au réseau interne… ██████████ OK', delay: 1200, cls: '' },
  { text: 'ATTENTION: Protocole de sécurité actif', delay: 800, cls: 'warning' },
  { text: 'Authentification requise.', delay: 600, cls: 'bright' },
];

/* ═══════════════  Action Codes  ═══════════════ */

export const ACTION_CODES = [
  {
    code: 'STATUS',
    response: [
      '╔══════════════════════════════════════╗',
      '║ ÉTAT DES SYSTÈMES DE L\'INSTALLATION ║',
      '╠══════════════════════════════════════╣',
      '║ Réseau interne .......... EN LIGNE   ║',
      '║ HELIX ............. COMPROMIS        ║',
      '║ Protocole ACTIF ......... 3   ║',
      '║ SEFY ........ VERROUILLÉ             ║',
      '╚══════════════════════════════════════╝',
    ],
  },
  {
    code: 'AIDE',
    response: ['Alias pour HELP.'],
    alias: 'HELP',
  },
];

/* ═══════════════  Virtual File System  ═══════════════
   tier: minimum accessTier required to read (default 1)
   ════════════════════════════════════════════════════════ */

export const FILE_SYSTEM = {
  '/': {
    type: 'dir',
    children: ['logs', 'audio', 'documents'],
  },
  '/admin_login.txt': {
    type: 'file',
    hidden: true,
    password: { question: 'Nom de mon chien ?', answer: 'RUFUS' },
    content: [
      '╔══════════════════════════════════════╗',
      '║         ADMIN LOGIN                  ║',
      '╠══════════════════════════════════════╣',
      '║  Code d\'accès: 61646D               ║',
      '╚══════════════════════════════════════╝',
    ],
  },
  '/logs': {
    type: 'dir',
    children: ['SYSTEM_ARCHIVED.log'],
  },
  '/logs/SYSTEM_ARCHIVED.log': {
    type: 'file',
    content: [
      '[2026-03-15 08:16] Système démarré normalement.',
      '[2026-03-15 14:32] Module SEFY: mise à jour automatique appliquée.',
      '[2026-03-15 23:56] HELIX scan débuté.',
      '[2026-03-16 00:01] HELIX scan Terminé.',
      '[2026-03-22 08:15] Système démarré normalement.',
      '[2026-03-22 14:31] Module SEFY: mise à jour automatique appliquée.',
      '[2026-03-22 23:57] HELIX scan débuté.',
      '[2026-03-23 00:02] HELIX scan Terminé.',
      '[2026-03-29 08:16] Système démarré normalement.',
      '[2026-03-29 14:33] Module SEFY: mise à jour automatique appliquée.',
      '[2026-03-29 23:55] HELIX scan débuté.',
      '[2026-03-30 00:00] HELIX scan Terminé.',
      '[2026-03-30 00:01] PRINT SEFY_INCIDENT_REPORT_2026-03-29.TXT',
      '[2026-04-06 08:16] Système démarré en état d\'alerte.',
      '[2026-04-06 14:31] Module SEFY: mise à jour automatique appliquée.',
      '[2026-04-06 23:57] HELIX scan débuté.',
      '[2026-04-07 00:02] HELIX scan Terminé.',
      '[2026-04-07 00:03] PRINT SEFY_INCIDENT_REPORT_2026-04-06.TXT',
      '[2026-04-08 22:45] PROTOCOLE 4 ACTIVÉ',
      '[2026-04-09 17:16] Système démarré en état d\'urgence.',
      '[2026-04-09 17:16] SEFY - LIRE PROCÉDURE D\'URGENCE.',
      '[2026-04-09 17:16] SEFY - VALIDATION DES ACCÈS.',
      '[2026-04-09 17:16] SEFY - APPLIQUE PROCÉDURE D\'URGENCE.',
      '[2026-04-09 17:17] PROTOCOLE 5 ACTIVÉ',
      '[2026-04-09 17:23] TENTATIVE de déactivation manuelle du PROTOCOLE 5',
      '[2026-04-09 17:23] SEFY - Halden, Victor Tier 3 - ACCÈS REFUSÉ',
      '[2026-04-09 17:26] TENTATIVE de déactivation manuelle de SEFY',
      '[2026-04-09 17:26] SEFY - Halden, Victor Tier 3 - ACCÈS REFUSÉ',
      '[2026-04-09 17:26] SEFY - APPLIQUE PROCÉDURE D\'URGENCE.',
      '[2026-04-09 17:35] HELIX scan débuté.',
      '[2026-04-09 17:36] TENTATIVE de déactivation manuelle du scan',
      '[2026-04-09 17:36] SEFY - Halden, Victor Tier 3 - ACCÈS REFUSÉ',
      '[2026-04-09 17:40] HELIX scan Terminé.',
      '[2026-04-09 17:40] PROTOCOLE 6 ACTIVÉ',
      '[2026-04-09 17:40] PROTOCOLE 7 ACTIVÉ',
      '[2026-04-09 17:40] SEFY - INITIALISATION DU PROTOCOLE 11',
      '[2026-04-09 17:41] SEFY - 10 minutes avant activation',
      '[2026-04-09 17:42] SEFY - 9 minutes avant activation',
      '[2026-04-09 17:43] SEFY - 8 minutes avant activation',
      '[2026-04-09 17:44] SEFY - 7 minutes avant activation',
      '[2026-04-09 17:45] SEFY - 6 minutes avant activation',
      '[2026-04-09 17:46] TENTATIVE de désactivation manuelle du PROTOCOLE 11',
      '[2026-04-09 17:46] SEFY - Marin, Élodie Tier 3 - ACCÈS REFUSÉ',
      '[2026-04-09 17:46] TENTATIVE de désactivation manuelle du PROTOCOLE 11',
      '[2026-04-09 17:46] SEFY - Marin, Élodie Tier 3 - ACCÈS REFUSÉ',
      '[2026-04-09 17:47] 5 minutes avant activation',
      '[2026-04-09 17:48] 4 minutes avant activation',
      '[2026-04-09 17:48] SEFY - Voss, Adrian Tier 4 - PROTOCOLE 8 - ACCÈS AUTORISÉ',
      '[2026-04-09 17:48] SEFY - Voss, Adrian Tier 4 - Outrepasse PROTOCOLE 7 - ACCÈS AUTORISÉ',
      '[2026-04-09 17:48] SEFY - Voss, Adrian Tier 4 - Commence téléversement sur intranet du fichier REPORT_2026-04-09.TXT',
      '[2026-04-09 17:48] [58 KO / 387 KO]',
      '[2026-04-09 17:48] [215 KO / 387 KO]',
      '[2026-04-09 17:49] SEFY - 3 minutes avant activation',
      '[2026-04-09 17:49] [381 KO / 387 KO]',
      '[2026-04-09 17:49] TENTATIVE de désactivation manuelle du PROTOCOLE 11',
      '[2026-04-09 17:49] SEFY - Marin, Élodie Tier 3 - ACCÈS REFUSÉ',
      '[2026-04-09 17:49] TENTATIVE de désactivation manuelle du PROTOCOLE 11',
      '[2026-04-09 17:50] SEFY - 2 minutes avant activation',
      '[2026-04-09 17:50] SEFY - Marin, Élodie Tier 3 - ACCÈS REFUSÉ',
      '[2026-04-09 17:50] TENTATIVE de désactivation manuelle de SEFY',
      '[2026-04-09 17:50] SEFY - Marin, Élodie Tier 3 - ACCÈS REFUSÉ',
      '[2026-04-09 17:50] TENTATIVE de désactivation manuelle du PROTOCOLE 11',
      '[2026-04-09 17:50] SEFY - Halden, Victor Tier 3 - ACCÈS REFUSÉ',
      '[2026-04-09 17:51] SEFY - 1 minutes avant activation',
      '[2026-04-09 17:51] PROTOCOLE 11 ACTIVÉ',
      '[2026-04-09 17:54] Réinitialisation des systèmes.',
      '[2026-04-09 17:57] SEFY - Système redémarré.',
      '[2026-04-09 17:57] SEFY - Accès restreint.',
      '[2026-05-01 00:28] Log system archivé.',
    ],
  },
  '/audio': {
    type: 'dir',
    children: [],
  },
  '/documents': {
    type: 'dir',
    children: ['employees', 
      'research_ark_41.txt', 
      'security_protocols_detailed.txt',
      'test_05_report.txt', 
      'test_17_report.txt', 
      'test_37_report.txt', 
      'test_43_report.txt',
      'test_subject_43_medical.txt'],
  },
  '/documents/employees': {
    type: 'dir',
    children: ['employee_accesses.txt', 
      'berger_thomas.txt', 
      'bouchard_karim.txt', 
      'delaney_marc.txt', 
      'gagnon_camille.txt', 
      'halden_victor.txt', 
      'ionescu_sofia.txt', 
      'klein_sarah.txt', 
      'marin_elodie.txt', 
      'moreau_lucas.txt', 
      'okada_hana.txt', 
      'park_julien.txt', 
      'petrov_nina.txt', 
      'rivera_alex.txt', 
      'voss_adrian.txt'],
  },
  '/documents/employees/employee_accesses.txt': {
    type: 'file',
    content: [
      'Berger, Thomas - Agent logistique - Tier 1',
      'Bouchard, Karim - Chercheur clinique - Tier 2',
      'Delaney, Marc - Analyste pathogènes - Tier 2',
      'Gagnon, Camille - Assistante recherche - Tier 1',
      'Halden, Victor - Responsable sécurité - Tier 3',
      'Ionescu, Sofia - Spécialiste génétique - Tier 2',
      'Klein, Sarah - Technicienne prélèvements - Tier 1',
      'Marin, Élodie - Directrice informatique - Tier 3',
      'Moreau, Lucas - Opérateur maintenance - Tier 1',
      'Okada, Hana - Immunologiste - Tier 2',
      'Park, Julien - Virologue senior - Tier 2',
      'Petrov, Nina - Support informatique - Tier 1',
      'Rivera, Alex - Technicien laboratoire - Tier 1',
      'Voss, Adrian - Chercheur principal - Tier 4',
    ],
    },
  '/documents/employees/berger_thomas.txt': {
    type: 'file',
    content: [
    'Berger, Thomas',
    'Poste : Agent logistique',
    'Niveau d\'accès : Tier 1',
    '',
    'Date de naissance : 14 mars 1985',
    'Téléphone : 418-555-0132',
    'Adresse : 284 rue des Pins, Québec, QC',
  ],
},
'/documents/employees/bouchard_karim.txt': {
    type: 'file',
    content: [
    'Bouchard, Karim',
    'Poste : Chercheur clinique',
    'Niveau d\'accès : Tier 2',
    '',
    'Date de naissance : 22 juillet 1981',
    'Téléphone : 514-555-0187',
    'Adresse : 1023 avenue Laurier, Montréal, QC',
  ],
},
'/documents/employees/delaney_marc.txt': {
    type: 'file',
    content: [
    'Delaney, Marc',
    'Poste : Analyste pathogènes',
    'Niveau d\'accès : Tier 2',
    '',
    'Date de naissance : 3 février 1979',
    'Téléphone : 438-555-0194',
    'Adresse : 77 boulevard René-Lévesque, Montréal, QC',
  ],
},
'/documents/employees/gagnon_camille.txt': {
    type: 'file',
    content: [
    'Gagnon, Camille',
    'Poste : Assistante recherche',
    'Niveau d\'accès : Tier 1',
    '',
    'Date de naissance : 9 novembre 1996',
    'Téléphone : 581-555-0108',
    'Adresse : 55 rue St-Paul, Québec, QC',
  ],
},
'/documents/employees/halden_victor.txt': {
    type: 'file',
    content: [
    'Halden, Victor',
    'Poste : Responsable sécurité',
    'Niveau d\'accès : Tier 3',
    '',
    'Date de naissance : 17 mai 1975',
    'Téléphone : 514-546-9672',
    'Adresse : 32 rue Sherbrooke O, Montréal, QC',
  ],
},
'/documents/employees/ionescu_sofia.txt': {
    type: 'file',
    content: [
    'Ionescu, Sofia',
    'Poste : Spécialiste génétique',
    'Niveau d\'accès : Tier 2',
    '',
    'Date de naissance : 28 septembre 1988',
    'Téléphone : 438-555-0156',
    'Adresse : 412 avenue du Parc, Montréal, QC',
  ],
},
'/documents/employees/klein_sarah.txt': {
    type: 'file',
    content: [
    'Klein, Sarah',
    'Poste : Technicienne prélèvements',
    'Niveau d\'accès : Tier 1',
    '',
    'Date de naissance : 6 janvier 1992',
    'Téléphone : 418-555-0141',
    'Adresse : 300 rue Cartier, Québec, QC',
  ],
},
'/documents/employees/marin_elodie.txt': {
    type: 'file',
    content: [
    'Marin, Élodie',
    'Poste : Directrice informatique',
    'Niveau d\'accès : Tier 3',
    '',
    'Date de naissance : 11 août 1980',
    'Téléphone : 514-555-0175',
    'Adresse : 1200 rue Peel, Montréal, QC',
  ],
},
'/documents/employees/moreau_lucas.txt': {
    type: 'file',
    content: [
    'Moreau, Lucas',
    'Poste : Opérateur maintenance',
    'Niveau d\'accès : Tier 1',
    '',
    'Date de naissance : 19 avril 1990',
    'Téléphone : 581-555-0129',
    'Adresse : 88 rue Marie-de-l\'Incarnation, Québec, QC',
  ],
},
'/documents/employees/okada_hana.txt': {
    type: 'file',
    content: [
    'Okada, Hana',
    'Poste : Immunologiste',
    'Niveau d\'accès : Tier 2',
    '',
    'Date de naissance : 30 décembre 1984',
    'Téléphone : 438-555-0168',
    'Adresse : 640 rue St-Denis, Montréal, QC',
  ],
},
'/documents/employees/park_julien.txt': {
    type: 'file',
    content: [
    'Park, Julien',
    'Poste : Virologue senior',
    'Niveau d\'accès : Tier 2',
    '',
    'Date de naissance : 25 juin 1983',
    'Téléphone : 514-555-0137',
    'Adresse : 200 rue Notre-Dame O, Montréal, QC',
  ],
},
'/documents/employees/petrov_nina.txt': {
    type: 'file',
    content: [
    'Petrov, Nina',
    'Poste : Support informatique',
    'Niveau d\'accès : Tier 1',
    '',
    'Date de naissance : 2 février 1995',
    'Téléphone : 438-555-0182',
    'Adresse : 715 rue Jean-Talon E, Montréal, QC',
  ],
},
'/documents/employees/rivera_alex.txt': {
    type: 'file',
    content: [
    'Rivera, Alex',
    'Poste : Technicien laboratoire',
    'Niveau d\'accès : Tier 1',
    '',
    'Date de naissance : 13 octobre 1993',
    'Téléphone : 581-555-0199',
    'Adresse : 410 rue Charest E, Québec, QC',
  ],
},
'/documents/employees/voss_adrian.txt': {
    type: 'file',
    content: [
    'Voss, Adrian',
    'Poste : Chercheur principal',
    'Niveau d\'accès : Tier 4',
    '',
    'Date de naissance : 8 septembre 1976',
    'Téléphone : 514-555-0101',
    'Adresse : 1 rue des Sciences, Montréal, QC',
  ],
},
'/documents/security_protocols_detailed.txt': {
    type: 'file',
    tier: 3,
    content: [
      'LABORATOIRE HELIX - LISTE DÉTAILLÉE DES PROTOCOLES DE SÉCURITÉ',
      '',
      'PROTOCOLE 1 - SURVEILLANCE STANDARD',
      'Active la surveillance normale des systèmes, des accès et des caméras.',
      '',
      'PROTOCOLE 2 - SAUVEGARDE DES DONNÉES',
      'Crée une copie de sécurité des journaux, dossiers et configurations système.',
      '',
      'PROTOCOLE 3 - RÉINITIALISATION COMPLÈTE DES SYSTÈMES',
      'Redémarre l\'ensemble des systèmes du laboratoire et recharge les paramètres par défaut.',
      '',
      'PROTOCOLE 4 - ALERTE ZONE RESTREINTE',
      'Déclenche une alerte lorsqu\'une présence ou une activité est détectée dans une zone interdite.',
      '',
      'PROTOCOLE 5 - VERROUILLAGE DU LABORATOIRE HELIX',
      'Ferme les accès principaux du site et limite les déplacements entre les secteurs.',
      '',
      'PROTOCOLE 6 - RESTRICTION DES COMMUNICATIONS',
      'Bloque ou filtre les communications internes et externes du laboratoire.',
      '',
      'PROTOCOLE 7 - VERROUILLAGE DES ACCÈS',
      'Empêche les utilisateurs de modifier certains systèmes ou de désactiver des procédures critiques.',
      '',
      'PROTOCOLE 8 - OVERRIDE MANUEL',
      'Override manuelle humaine en cours pour interrompre une procédure active.',
      '',
      'PROTOCOLE 9 - SURVEILLANCE INTERNE ACTIVE',
      'Renforce la surveillance en temps réel des pièces, terminaux et mouvements internes.',
      '',
      'PROTOCOLE 10 - PROCÉDURE DE CONFINEMENT',
      'Isole les zones à risque afin d\'éviter la propagation de matériaux biologiques dangereux.',
      '',
      'PROTOCOLE 11 - PURGE',
      'Procédure de dernier recours visant à neutraliser intégralement une menace critique au sein du laboratoire.',
    ],
  },
    '/documents/research_ark_41.txt': {
      type: 'file',
      tier: 2,
      content: [
        'LABORATOIRE HELIX - DIVISION GÉNÉTIQUE',
        'PROJET : MODIFICATION VIRUS ARK 41',
        '',
        'Objectif :',
        'Modifier certains virus afin de mieux comprendre leur comportement.',
        '',
        'Tests en cours :',
        '- Étude de la résistance à la chaleur.',
        '- Étude de la propagation entre cellules.',
        '- Observation des mutations.',
        '',
        'Résultats partiels :',
        'Certaines souches se propagent plus rapidement que prévu.',
        '',
        'Note :',
        'Tous les échantillons doivent rester dans les zones sécurisées.',
        '',
        'Statut : ACTIF',
      ],
    },
  '/documents/test_05_report.txt': {
      type: 'file',
      tier: 2,
      content: [
        'LABORATOIRE HELIX - RAPPORT DE TEST',
        'TEST 05',
        '',
        'Objectif :',
        'Vérifier la stabilité de la souche ARK-41 en environnement contrôlé.',
        '',
        'Procédure :',
        'La souche a été exposée à différentes températures et niveaux d\'humidité.',
        '',
        'Résultat : ÉCHEC',
        'La souche s\'est dégradée rapidement.',
        'Perte complète d\'activité après 3 heures.',
        '',
        'Conclusion :',
        'La souche est trop instable pour utilisation.',
        'Ajustements génétiques nécessaires.',
        '',
        'Statut : ARCHIVÉ',
      ]
    },
    '/documents/test_17_report.txt': {
      type: 'file',
      tier: 2,
      content: [
        'LABORATOIRE HELIX - RAPPORT DE TEST',
        'TEST 17',
        '',
        'Objectif :',
        'Améliorer la résistance de la souche modifiée.',
        '',
        'Procédure :',
        'Modification de la structure génétique pour augmenter la stabilité.',
        '',
        'Résultat : ÉCHEC',
        'La souche perd sa structure après exposition.',
        'Mutation imprévue détectée.',
        '',
        'Conclusion :',
        'Approche actuelle inefficace.',
        'Changement de méthode recommandé.',
        '',
        'Statut : APPROUVÉ',
      ],
    },
    '/documents/test_37_report.txt': {
      type: 'file',
      tier: 2,
      content: [
        'LABORATOIRE HELIX - RAPPORT DE TEST',
        'TEST 37',
        '',
        'Objectif :',
        'Observer l\'adaptation de la nouvelle souche.',
        '',
        'Procédure :',
        'La souche a été testée sur un modèle biologique simulé.',
        '',
        'Résultat : PARTIEL',
        'La souche reste active plus longtemps.',
        'Capacité d\'adaptation observée.',
        '',
        'Observation :',
        'Réaction différente de celle attendue.',
        '',
        'Recommandation :',
        'Envisager test sur sujet humain.',
        '',
        'Statut : APPROUVÉ',
      ],
    },
    '/documents/test_subject_43_medical.txt': {
      type: 'file',
      tier: 3,
      content: [
        'LABORATOIRE HELIX - DOSSIER MÉDICAL',
        'SUJET : 43-A',
        '',
        'Nom : Silvayn Dupont',
        'Age : 34 ans',
        '',
        'Profil :',
        'Adulte en bonne santé.',
        'Aucun antécédent médical majeur.',
        '',
        'Procédure :',
        'Injection contrôlée de la souche expérimentale.',
        'Surveillance continue pendant 24 heures.',
        '',
        'Observations :',
        'Augmentation légère de la température corporelle.',
        'Fatigue signalée après 6 heures.',
        'Aucune douleur importante.',
        '',
        'Signes positifs :',
        'Le corps du sujet réagit comme prévu.',
        'La souche reste stable.',
        '',
        'Effets secondaires :',
        'Maux de tête temporaires.',
        'Frissons légers.',
        '',
        'Conclusion :',
        'Résultat conforme aux attentes.',
        'Surveillance prolongée recommandée.',
        '',
        'Statut : ÉTUDE EN COURS',
      ],
    },
    '/documents/test_43_report.txt': {
      type: 'file',
      tier: 3,
      content: [
        'LABORATOIRE HELIX - RAPPORT DE TEST',
        'TEST 43',
        '',
        'Objectif :',
        'Valider la stabilité finale de la souche.',
        '',
        'Procédure :',
        'Test effectué sur sujet humain volontaire sous supervision.',
        '',
        'Résultat : SUCCÈS',
        'La souche reste stable.',
        'Réaction mesurable observée.',
        '',
        'Observation :',
        'Adaptation rapide du sujet.',
        'Effets secondaires à surveiller.',
        '',
        'Action :',
        'Début de l\'étude de cas.',
        '',
        'Statut : ACTIF',
      ],
    },
  };
